repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args:
          - --profile=black
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3
        types: [ python ]
  - repo: https://github.com/myint/autoflake
    rev: v1.7.1
    hooks:
      - id: autoflake
        language_version: python3
        types: [ python ]
        args:
          - --remove-all-unused-imports
          - --recursive
          - --in-place
