name: publish
on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install twine

      - name: Build
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        run: |
          twine upload -r testpypi dist/*
